___

<a href='http://www.pieriandata.com'> <img src='../Pierian_Data_Logo.png' /></a>
___

# DataFrames

DataFrames are the workhorse of pandas and are directly inspired by the R programming language. We can think of a DataFrame as a bunch of Series objects put together to share the same index. Let's use pandas to explore this topic!

In [16]:
import pandas as pd
import numpy as np

In [17]:
from numpy.random import randn
np.random.seed(101) #seed allows us to retain the random generated

In [18]:
pd.DataFrame()

Empty DataFrame
Columns: []
Index: []

In [19]:
data = pd.DataFrame(randn(5,4),index=['A', 'B', 'C', 'D', 'E'],columns='W X Y Z'.split())
#5rows, 4 columns

In [20]:
data

          W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [21]:
data.head() #top 5 records (rows and columns)

          W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [22]:
data.head(7)

          W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [23]:
data.head(10) #show the top 10 records

          W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [24]:
data.tail(10) #bottom last 5records

          W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [25]:
data.shape #shape shows the number of rows and columns 5 rows, 4 columns

(5, 4)

## Selection and Indexing

Let's learn the various methods to grab data from a DataFrame

In [26]:
data['Y']

A    0.907969
B   -0.848077
C    0.528813
D   -0.933237
E    2.605967
Name: Y, dtype: float64

In [27]:
# Pass a list of column names
data[['W','Z', 'X']]

          W         Z         X
A  2.706850  0.503826  0.628133
B  0.651118  0.605965 -0.319318
C -2.018168 -0.589001  0.740122
D  0.188695  0.955057 -0.758872
E  0.190794  0.683509  1.978757

In [28]:
# SQL Syntax (NOT RECOMMENDED!)
data['W']

A    2.706850
B    0.651118
C   -2.018168
D    0.188695
E    0.190794
Name: W, dtype: float64

DataFrame Columns are just Series

In [29]:
type(data['W'])

pandas.core.series.Series

**Creating a new column:**

In [35]:
data['Sum of WY'] = data['W'] + data['Y']
data['Sum of XZ'] = data['X'] + data['Z']



#data['age'] = 2025 - data['dob']
#create a column called Age, a column called year
#data['age'] = 2025 - data['year']

In [36]:
data.head()

          W         X         Y         Z  Sum of WY  Sum of XZ
A  2.706850  0.628133  0.907969  0.503826   3.614819   1.131958
B  0.651118 -0.319318 -0.848077  0.605965  -0.196959   0.286647
C -2.018168  0.740122  0.528813 -0.589001  -1.489355   0.151122
D  0.188695 -0.758872 -0.933237  0.955057  -0.744542   0.196184
E  0.190794  1.978757  2.605967  0.683509   2.796762   2.662266

In [37]:
data

          W         X         Y         Z  Sum of WY  Sum of XZ
A  2.706850  0.628133  0.907969  0.503826   3.614819   1.131958
B  0.651118 -0.319318 -0.848077  0.605965  -0.196959   0.286647
C -2.018168  0.740122  0.528813 -0.589001  -1.489355   0.151122
D  0.188695 -0.758872 -0.933237  0.955057  -0.744542   0.196184
E  0.190794  1.978757  2.605967  0.683509   2.796762   2.662266

In [38]:
data.drop('Sum of XZ',axis=1, inplace=True) #axis =1 means in a column, axis=0 means in a row, inplace = True (drop permanently)

In [39]:
data.head()

          W         X         Y         Z  Sum of WY
A  2.706850  0.628133  0.907969  0.503826   3.614819
B  0.651118 -0.319318 -0.848077  0.605965  -0.196959
C -2.018168  0.740122  0.528813 -0.589001  -1.489355
D  0.188695 -0.758872 -0.933237  0.955057  -0.744542
E  0.190794  1.978757  2.605967  0.683509   2.796762

** Removing Columns**

In [40]:
data.drop(['Sum of WY', 'X'],axis=1)

          W         Y         Z
A  2.706850  0.907969  0.503826
B  0.651118 -0.848077  0.605965
C -2.018168  0.528813 -0.589001
D  0.188695 -0.933237  0.955057
E  0.190794  2.605967  0.683509

In [45]:
# Not inplace unless specified!
data

          W         X         Y         Z  Sum of WY
A  2.706850  0.628133  0.907969  0.503826   3.614819
B  0.651118 -0.319318 -0.848077  0.605965  -0.196959
C -2.018168  0.740122  0.528813 -0.589001  -1.489355
D  0.188695 -0.758872 -0.933237  0.955057  -0.744542
E  0.190794  1.978757  2.605967  0.683509   2.796762

** Selecting Rows**

In [48]:
data.loc['A'] #access the row

W            2.706850
X            0.628133
Y            0.907969
Z            0.503826
Sum of WY    3.614819
Name: A, dtype: float64

In [49]:
data['X'] #acces the column

A    0.628133
B   -0.319318
C    0.740122
D   -0.758872
E    1.978757
Name: X, dtype: float64

In [50]:
data.loc['E']

W            0.190794
X            1.978757
Y            2.605967
Z            0.683509
Sum of WY    2.796762
Name: E, dtype: float64

Or select based off of position instead of label

In [51]:
data.head()

          W         X         Y         Z  Sum of WY
A  2.706850  0.628133  0.907969  0.503826   3.614819
B  0.651118 -0.319318 -0.848077  0.605965  -0.196959
C -2.018168  0.740122  0.528813 -0.589001  -1.489355
D  0.188695 -0.758872 -0.933237  0.955057  -0.744542
E  0.190794  1.978757  2.605967  0.683509   2.796762

In [52]:
data.iloc[2] #index

W           -2.018168
X            0.740122
Y            0.528813
Z           -0.589001
Sum of WY   -1.489355
Name: C, dtype: float64

** Selecting subset of rows and columns **

In [24]:
data

          W         X         Y         Z  Sum of WY
A  2.706850  0.628133  0.907969  0.503826   3.614819
B  0.651118 -0.319318 -0.848077  0.605965  -0.196959
C -2.018168  0.740122  0.528813 -0.589001  -1.489355
D  0.188695 -0.758872 -0.933237  0.955057  -0.744542
E  0.190794  1.978757  2.605967  0.683509   2.796762

In [25]:
data.loc['B','Y']

-0.8480769834036315

In [26]:
data.loc[['A','B'],['W','Y']]

          W         Y
A  2.706850  0.907969
B  0.651118 -0.848077

### Conditional Selection

An important feature of pandas is conditional selection using bracket notation, very similar to numpy:

In [27]:
data

          W         X         Y         Z  Sum of WY
A  2.706850  0.628133  0.907969  0.503826   3.614819
B  0.651118 -0.319318 -0.848077  0.605965  -0.196959
C -2.018168  0.740122  0.528813 -0.589001  -1.489355
D  0.188695 -0.758872 -0.933237  0.955057  -0.744542
E  0.190794  1.978757  2.605967  0.683509   2.796762

In [41]:
data[data<0]

          W        X         Y         Z  Sum of WY
A       NaN      NaN -0.376519       NaN        NaN
B       NaN      NaN -0.031160       NaN        NaN
C -1.005187 -0.74179       NaN -0.732845  -0.818062
D -1.382920      NaN       NaN -2.141212  -0.421462
E       NaN      NaN -1.046780       NaN  -0.054206

In [30]:
data[data>0]

          W         X         Y         Z  Sum of WY
A  2.706850  0.628133  0.907969  0.503826   3.614819
B  0.651118       NaN       NaN  0.605965        NaN
C       NaN  0.740122  0.528813       NaN        NaN
D  0.188695       NaN       NaN  0.955057        NaN
E  0.190794  1.978757  2.605967  0.683509   2.796762

In [32]:
data[data['W']<0]

          W         X         Y         Z  Sum of WY
C -2.018168  0.740122  0.528813 -0.589001  -1.489355

In [33]:
data[data['W']>0]['W']

A    2.706850
B    0.651118
D    0.188695
E    0.190794
Name: W, dtype: float64

In [34]:
data[data>0][['Y','X']]

          Y         X
A  0.907969  0.628133
B       NaN       NaN
C  0.528813  0.740122
D       NaN       NaN
E  2.605967  1.978757

For two conditions you can use | and & with parenthesis:

In [35]:
data[(data>0) & (data['Y'] > 1)]

    W   X   Y   Z  Sum of WY
A NaN NaN NaN NaN        NaN
B NaN NaN NaN NaN        NaN
C NaN NaN NaN NaN        NaN
D NaN NaN NaN NaN        NaN
E NaN NaN NaN NaN        NaN

## More Index Details

Let's discuss some more features of indexing, including resetting the index or setting it something else. We'll also talk about index hierarchy!

In [36]:
data

          W         X         Y         Z  Sum of WY
A  2.706850  0.628133  0.907969  0.503826   3.614819
B  0.651118 -0.319318 -0.848077  0.605965  -0.196959
C -2.018168  0.740122  0.528813 -0.589001  -1.489355
D  0.188695 -0.758872 -0.933237  0.955057  -0.744542
E  0.190794  1.978757  2.605967  0.683509   2.796762

In [37]:
# Reset to default 0,1...n index
data.reset_index(inplace=True)  #reset the value or the index to default

In [38]:
data

  index         W         X         Y         Z  Sum of WY
0     A  2.706850  0.628133  0.907969  0.503826   3.614819
1     B  0.651118 -0.319318 -0.848077  0.605965  -0.196959
2     C -2.018168  0.740122  0.528813 -0.589001  -1.489355
3     D  0.188695 -0.758872 -0.933237  0.955057  -0.744542
4     E  0.190794  1.978757  2.605967  0.683509   2.796762

In [39]:
data.drop('index', axis=1, inplace=True)

In [55]:
df.drop(['level_0','index'], axis=1, inplace=True)

In [41]:
data.columns

Index(['W', 'X', 'Y', 'Z', 'Sum of WY'], dtype='object')

In [53]:
newind = 'CA NY WY OR CO'.split()

#newind = ['s', 'd']

In [54]:
data['States'] = newind

In [ ]:
data['states'] = 'CA NY WY OR CO'.split()

In [55]:
data

          W         X         Y         Z  Sum of WY States
A  2.706850  0.628133  0.907969  0.503826   3.614819     CA
B  0.651118 -0.319318 -0.848077  0.605965  -0.196959     NY
C -2.018168  0.740122  0.528813 -0.589001  -1.489355     WY
D  0.188695 -0.758872 -0.933237  0.955057  -0.744542     OR
E  0.190794  1.978757  2.605967  0.683509   2.796762     CO

In [56]:
data.set_index('States', inplace=True)

In [57]:
data.columns

Index(['W', 'X', 'Y', 'Z', 'Sum of WY'], dtype='object')

In [58]:
data

               W         X         Y         Z  Sum of WY
States
CA      2.706850  0.628133  0.907969  0.503826   3.614819
NY      0.651118 -0.319318 -0.848077  0.605965  -0.196959
WY     -2.018168  0.740122  0.528813 -0.589001  -1.489355
OR      0.188695 -0.758872 -0.933237  0.955057  -0.744542
CO      0.190794  1.978757  2.605967  0.683509   2.796762

In [59]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 5 entries, CA to CO
Data columns (total 5 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   W          5 non-null      float64
 1   X          5 non-null      float64
 2   Y          5 non-null      float64
 3   Z          5 non-null      float64
 4   Sum of WY  5 non-null      float64
dtypes: float64(5)
memory usage: 240.0+ bytes

In [60]:
data.shape

(5, 5)

In [61]:
data.isnull().sum()

W            0
X            0
Y            0
Z            0
Sum of WY    0
dtype: int64

In [27]:
data.isnull().sum() #to check if there are missing data 

data['W']

A    0.302665
B   -0.134841
C    0.807706
D   -0.497104
E   -0.116773
Name: W, dtype: float64

In [53]:
data

               W         X         Y         Z  Sum of WY
States
CA      2.706850  0.628133  0.907969  0.503826   3.614819
NY      0.651118 -0.319318 -0.848077  0.605965  -0.196959
WY     -2.018168  0.740122  0.528813 -0.589001  -1.489355
OR      0.188695 -0.758872 -0.933237  0.955057  -0.744542
CO      0.190794  1.978757  2.605967  0.683509   2.796762

In [41]:
df.set_index('States',inplace=True)

In [62]:
data.reset_index(inplace = True)

In [63]:
data

  States         W         X         Y         Z  Sum of WY
0     CA  2.706850  0.628133  0.907969  0.503826   3.614819
1     NY  0.651118 -0.319318 -0.848077  0.605965  -0.196959
2     WY -2.018168  0.740122  0.528813 -0.589001  -1.489355
3     OR  0.188695 -0.758872 -0.933237  0.955057  -0.744542
4     CO  0.190794  1.978757  2.605967  0.683509   2.796762

## Multi-Index and Index Hierarchy

Let us go over how to work with Multi-Index, first we'll create a quick example of what a Multi-Indexed DataFrame would look like:

In [57]:
# Index Levels
outside = ['G1','G1','G1','G2','G2','G2']
inside = [1,2,3,1,2,3]
hier_index = list(zip(outside,inside))
hier_index = pd.MultiIndex.from_tuples(hier_index)

In [58]:
hier_index

MultiIndex([('G1', 1),
            ('G1', 2),
            ('G1', 3),
            ('G2', 1),
            ('G2', 2),
            ('G2', 3)],
           )

In [59]:
df = pd.DataFrame(np.random.randn(6,2),index=hier_index,columns=['A','B'])
df

             A         B
G1 1  0.302665  1.693723
   2 -1.706086 -1.159119
   3 -0.134841  0.390528
G2 1  0.166905  0.184502
   2  0.807706  0.072960
   3  0.638787  0.329646

Now let's show how to index this! For index hierarchy we use df.loc[], if this was on the columns axis, you would just use normal bracket notation df[]. Calling one level of the index returns the sub-dataframe:

In [60]:
df.loc['G1']

          A         B
1  0.302665  1.693723
2 -1.706086 -1.159119
3 -0.134841  0.390528

In [61]:
df.loc['G1'].loc[1]

A    0.302665
B    1.693723
Name: 1, dtype: float64

In [51]:
df.index.names

FrozenList([None, None])

In [52]:
df.index.names = ['Group','Num']

In [53]:
df

                  A         B
Group Num
G1    1    0.147027 -0.479448
      2    0.558769  1.024810
      3   -0.925874  1.862864
G2    1   -1.133817  0.610478
      2    0.386030  2.084019
      3   -0.376519  0.230336

In [54]:
df.xs('G1')

            A         B
Num
1    0.147027 -0.479448
2    0.558769  1.024810
3   -0.925874  1.862864

In [55]:
df.xs(['G1',1])

A    0.147027
B   -0.479448
Name: (G1, 1), dtype: float64

In [56]:
df.xs(1,level='Num')

              A         B
Group
G1     0.147027 -0.479448
G2    -1.133817  0.610478

# Great Job!