___

<a href='http://www.pieriandata.com'> <img src='../Pierian_Data_Logo.png' /></a>
___

# Groupby

The groupby method allows you to group rows of data together and call aggregate functions

In [1]:
import pandas as pd
# Create dataframe
data = {'Company':['GOOG','GOOG','MSFT','MSFT','FB','FB'],'Person':['Sam','Charlie','Amy','Vanessa','Carl','Sarah'],'Sales':[200,120,340,124,243,350]}

In [2]:
df = pd.DataFrame(data)

In [3]:
df.shape

(6, 3)

In [7]:
df.head(10)

  Company   Person  Sales
0    GOOG      Sam    200
1    GOOG  Charlie    120
2    MSFT      Amy    340
3    MSFT  Vanessa    124
4      FB     Carl    243
5      FB    Sarah    350

In [8]:
df

  Company   Person  Sales
0    GOOG      Sam    200
1    GOOG  Charlie    120
2    MSFT      Amy    340
3    MSFT  Vanessa    124
4      FB     Carl    243
5      FB    Sarah    350

In [6]:
df.shape

(6, 3)

** Now you can use the .groupby() method to group rows together based on a column name. For instance let's group based on Company. This will create a DataFrameGroupBy object:**

In [9]:
df.groupby('Company')

You can save this object as a new variable:

In [12]:
by_comp = df.groupby("Company")

In [13]:
by_comp.head()

  Company   Person  Sales
0    GOOG      Sam    200
1    GOOG  Charlie    120
2    MSFT      Amy    340
3    MSFT  Vanessa    124
4      FB     Carl    243
5      FB    Sarah    350

And then call aggregate methods off the object:

In [14]:
by_comp.sum()

             Person  Sales
Company
FB        CarlSarah    593
GOOG     SamCharlie    320
MSFT     AmyVanessa    464

In [21]:
by_comp.sum()

             Person  Sales
Company
FB        CarlSarah    593
GOOG     SamCharlie    320
MSFT     AmyVanessa    464

In [15]:
by_comp.max()

          Person  Sales
Company
FB         Sarah    350
GOOG         Sam    200
MSFT     Vanessa    340

In [16]:
by_comp.min()

          Person  Sales
Company
FB          Carl    243
GOOG     Charlie    120
MSFT         Amy    124

In [24]:
by_comp.max()

          Person  Sales
Company
FB         Sarah    350
GOOG         Sam    200
MSFT     Vanessa    340

In [17]:
by_comp.count()

         Person  Sales
Company
FB            2      2
GOOG          2      2
MSFT          2      2

In [13]:
by_comp.describe() #stastistical analsysis

        Sales
        count   mean         std    min     25%    50%     75%    max
Company
FB        2.0  296.5   75.660426  243.0  269.75  296.5  323.25  350.0
GOOG      2.0  160.0   56.568542  120.0  140.00  160.0  180.00  200.0
MSFT      2.0  232.0  152.735065  124.0  178.00  232.0  286.00  340.0

In [18]:
by_comp.describe().transpose()['MSFT']

Sales  count      2.000000
       mean     232.000000
       std      152.735065
       min      124.000000
       25%      178.000000
       50%      232.000000
       75%      286.000000
       max      340.000000
Name: MSFT, dtype: float64

In [17]:
by_comp.describe().transpose()['FB']

Sales  count      2.000000
       mean     296.500000
       std       75.660426
       min      243.000000
       25%      269.750000
       50%      296.500000
       75%      323.250000
       max      350.000000
Name: FB, dtype: float64

In [19]:
df['profit'] = [100,200,300,400,500,600]

In [27]:
df.head(7)

  Company   Person  Sales  profit
0    GOOG      Sam    200     100
1    GOOG  Charlie    120     200
2    MSFT      Amy    340     300
3    MSFT  Vanessa    124     400
4      FB     Carl    243     500
5      FB    Sarah    350     600

In [22]:
new =df.groupby('Company').sum()

In [23]:
new

             Person  Sales  profit
Company
FB        CarlSarah    593    1100
GOOG     SamCharlie    320     300
MSFT     AmyVanessa    464     700

In [35]:
df.shape

(6, 4)

In [13]:
#class work 
#create a new column named supervisor, assign values, them split 
#add the new column to the data data frame
#groupby and perfom some aggregrate function 

df['supervisor'] = 'ola femi ope korede funmilayo seyi'.split()

In [14]:
df.head()

  Company   Person  Sales supervisor
0    GOOG      Sam    200        ola
1    GOOG  Charlie    120       femi
2    MSFT      Amy    340        ope
3    MSFT  Vanessa    124     korede
4      FB     Carl    243  funmilayo

In [18]:
new =df.groupby('Company').sum()

In [16]:
new

             Person  Sales     supervisor
Company
FB        CarlSarah    593  funmilayoseyi
GOOG     SamCharlie    320        olafemi
MSFT     AmyVanessa    464      opekorede

# Great Job!